### ISSUE TITLE
Namespaces aren't imported when pushing code on Codingame

### ISSUE THREAD

**Issue by nalka0** [dk588/CodingGameExtension#16]
When pushing the current code to Codingame using the "Push code" or "Push and play" button, the following code
```cs
namespace ExampleNamespace
{
    public class ExampleClass
    {

    }
}
```
and
```cs
namespace ExampleNamespace;
public class ExampleClass
{
}
```
are pushed as
```cs
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
    public class ExampleClass
    {

    }
```
This will make your code compile on Visual Studio but not on Codingame when your code has a reference to any of your namespaces.

On a side note, file-scoped namespaces would have to be converted to block-scoped namespaces when pushing to codingame else you'll get CS8954 on Codingame if there are several namespaces on your project.

**Comment by dk588** [comment]
Hi Nalka, Thanks for the feedback. I didn't know codingame can manage namespace, As by default, there's no namespace in the code sample. I'll do some test and check asap.
